'use client';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { useTheme } from '@/components/useTheme';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FaFileCsv, FaFileExcel, FaFilePdf } from 'react-icons/fa';
import { HiDownload } from 'react-icons/hi';

export interface ExportButtonsProps {
  filename: string;
  headers: string[];
  rows: (string | number | null | undefined)[][];
}

type Format = 'csv' | 'xlsx' | 'pdf';

async function exportViaApi(
  format: 'csv' | 'xlsx',
  filename: string,
  headers: string[],
  rows: ExportButtonsProps['rows'],
) {
  const res = await fetch('/api/export', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ format, filename, headers, rows }),
  });
  if (!res.ok) throw new Error('Export failed');
  const blob = await res.blob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.${format === 'xlsx' ? 'xlsx' : 'csv'}`;
  a.click();
  URL.revokeObjectURL(url);
}

async function exportPdf(
  filename: string,
  headers: string[],
  rows: ExportButtonsProps['rows'],
) {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  // Try to load the logo
  let logoBase64: string | null = null;
  try {
    const res = await fetch('/logo-sm.png');
    const blob = await res.blob();
    logoBase64 = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch { /* skip if logo not found */ }

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm' });
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  const exportedOn = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });

  // Title
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 15, 15);
  doc.text(filename, 14, 15);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Exported ${exportedOn}`, 14, 21);
  doc.setTextColor(0, 0, 0);

  // Table
  autoTable(doc, {
    startY: 27,
    head: [headers],
    body: rows.map(r => r.map(v => (v == null ? '' : String(v)))),
    styles: {
      fontSize: 7.5,
      cellPadding: { top: 2, right: 2.5, bottom: 2, left: 2.5 },
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [109, 40, 217],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    alternateRowStyles: { fillColor: [248, 248, 252] },
    margin: { left: 14, right: 14, bottom: 16 },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.1,
  });

  // Footer on every page: logo + line + "Generated by Readi" + page number
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (logoBase64) {
      doc.addImage(logoBase64, 'PNG', pageW - 26, 5, 12, 12);
    }
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(14, pageH - 12, pageW - 14, pageH - 12);
    doc.setLineWidth(0.2);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by Readi Platform', 14, pageH - 7);
    doc.text(`Page ${i} of ${totalPages}`, pageW - 14, pageH - 7, { align: 'right' });
  }

  doc.save(`${filename}.pdf`);
}

export default function ExportButtons({ filename, headers, rows }: ExportButtonsProps) {
  const { t } = useTranslation();
  const { isDark } = useTheme();
  const [loading, setLoading] = useState<Format | null>(null);

  const handle = async (format: Format) => {
    setLoading(format);
    try {
      if (format === 'pdf') {
        await exportPdf(filename, headers, rows);
      } else {
        await exportViaApi(format, filename, headers, rows);
      }
    } catch (e) {
      console.error('Export error:', e);
    } finally {
      setLoading(null);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <button
          disabled={!!loading}
          className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md border text-xs font-medium transition-colors disabled:opacity-60 disabled:cursor-not-allowed
            ${isDark
              ? 'border-slate-700 bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white'
              : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50 hover:text-slate-900'
            }`}
        >
          <HiDownload className="w-3.5 h-3.5" />
          {loading ? t('export.exporting') : t('export.export')}
        </button>
      </DropdownMenuTrigger>

      <DropdownMenuContent
        align="start"
        className={`min-w-44 ${isDark ? 'bg-slate-800 border-slate-700 text-slate-200' : ''}`}
      >
        <DropdownMenuLabel
          className={`text-[10px] uppercase tracking-widest ${isDark ? 'text-slate-500' : 'text-slate-400'}`}
        >
          {t('export.downloadAs')}
        </DropdownMenuLabel>
        <DropdownMenuSeparator className={isDark ? 'bg-slate-700' : ''} />

        <DropdownMenuItem
          onClick={() => handle('csv')}
          disabled={!!loading}
          className={`text-xs gap-2 cursor-pointer ${isDark ? 'hover:bg-slate-700' : ''}`}
        >
          <FaFileCsv className="w-3.5 h-3.5 text-emerald-600" />
          CSV (.csv)
          {loading === 'csv' && <span className="ml-auto text-[10px] opacity-60">…</span>}
        </DropdownMenuItem>

        <DropdownMenuItem
          onClick={() => handle('xlsx')}
          disabled={!!loading}
          className={`text-xs gap-2 cursor-pointer ${isDark ? 'hover:bg-slate-700' : ''}`}
        >
          <FaFileExcel className="w-3.5 h-3.5 text-emerald-600" />
          Excel (.xlsx)
          {loading === 'xlsx' && <span className="ml-auto text-[10px] opacity-60">…</span>}
        </DropdownMenuItem>

        <DropdownMenuItem
          onClick={() => handle('pdf')}
          disabled={!!loading}
          className={`text-xs gap-2 cursor-pointer ${isDark ? 'hover:bg-slate-700' : ''}`}
        >
          <FaFilePdf className="w-3.5 h-3.5 text-red-500" />
          PDF (.pdf)
          {loading === 'pdf' && <span className="ml-auto text-[10px] opacity-60">…</span>}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
