
import { Document, DocumentType, Notifications, SafetyIndicator } from '../config/types';
export const DUMMY_DOCUMENTS: Document[] = [
  {
    document_id: 1,
    doc_type_id: 1,
    doc_code: 'LUC-COMP-001',
    title: 'Safety Management System Manual',
    description: 'Comprehensive manual for safety management procedures and protocols',
    status: 'APPROVED',
    area: 'COMPLIANCE',
    category: 'Manual',
    confidentiality: 'INTERNAL',
    owner_role: 'Compliance Manager',
    effective_date: '2024-01-01',
    expiry_date: '2025-01-01',
    keywords: 'safety, management, procedures, compliance',
    tags: '["safety", "compliance", "manual"]',
    version_label: 'v2.1',
    change_log: 'Updated regulatory requirements for 2024',
    file_path: '/uploads/docs/luc-comp-001-v2.1.pdf',
    created_at: '2024-01-15T10:30:00',
    updated_at: '2024-01-20T14:45:00',
    type_name: 'Safety Manual',
  },
  {
    document_id: 2,
    doc_type_id: 2,
    doc_code: 'LUC-TRAIN-002',
    title: 'Pilot Training Curriculum',
    description: 'Complete training curriculum for drone pilots including theoretical and practical components',
    status: 'APPROVED',
    area: 'TRAINING',
    category: 'Curriculum',
    confidentiality: 'INTERNAL',
    owner_role: 'Training Manager',
    effective_date: '2024-02-01',
    expiry_date: '2025-02-01',
    keywords: 'training, pilot, curriculum, education',
    tags: '["training", "pilot", "education"]',
    version_label: 'v1.5',
    change_log: 'Added new modules for advanced flight operations',
    file_path: '/uploads/docs/luc-train-002-v1.5.pdf',
    created_at: '2024-01-10T09:00:00',
    updated_at: '2024-01-28T16:20:00',
    type_name: 'Training Document',
  },
  {
    document_id: 3,
    doc_type_id: 3,
    doc_code: 'LUC-OPS-003',
    title: 'Standard Operating Procedures',
    description: 'Standard operating procedures for daily drone operations',
    status: 'IN_REVIEW',
    area: 'OPERATION',
    category: 'Procedure',
    confidentiality: 'INTERNAL',
    owner_role: 'Operations Manager',
    effective_date: '2024-03-01',
    keywords: 'operations, procedures, SOP, daily operations',
    tags: '["operations", "SOP"]',
    version_label: 'v3.0-draft',
    change_log: 'Major revision for new operational requirements',
    file_path: '/uploads/docs/luc-ops-003-v3.0-draft.pdf',
    created_at: '2024-02-01T11:15:00',
    updated_at: '2024-02-03T10:30:00',
    type_name: 'SOP Document',
  },
  {
    document_id: 4,
    doc_type_id: 4,
    doc_code: 'LUC-MAINT-004',
    title: 'Maintenance Schedule and Checklist',
    description: 'Scheduled maintenance procedures and inspection checklists for all drone models',
    status: 'APPROVED',
    area: 'MAINTENANCE',
    category: 'Checklist',
    confidentiality: 'INTERNAL',
    owner_role: 'Maintenance Chief',
    effective_date: '2024-01-15',
    expiry_date: '2024-12-31',
    keywords: 'maintenance, inspection, checklist, schedule',
    tags: '["maintenance", "inspection"]',
    version_label: 'v1.2',
    change_log: 'Updated checklist items for new drone models',
    file_path: '/uploads/docs/luc-maint-004-v1.2.pdf',
    created_at: '2024-01-05T08:45:00',
    updated_at: '2024-01-15T13:10:00',
    type_name: 'Maintenance Document',
  },
  {
    document_id: 5,
    doc_type_id: 5,
    doc_code: 'LUC-SEC-005',
    title: 'Data Security and Privacy Policy',
    description: 'Policies and procedures for data security and privacy protection',
    status: 'APPROVED',
    area: 'SECURITY',
    category: 'Policy',
    confidentiality: 'CONFIDENTIAL',
    owner_role: 'Security Officer',
    effective_date: '2024-01-01',
    expiry_date: '2025-01-01',
    keywords: 'security, privacy, data protection, GDPR',
    tags: '["security", "privacy", "GDPR"]',
    version_label: 'v2.0',
    change_log: 'Updated for GDPR compliance requirements',
    file_path: '/uploads/docs/luc-sec-005-v2.0.pdf',
    created_at: '2023-12-15T14:00:00',
    updated_at: '2024-01-01T09:00:00',
    type_name: 'Security Policy',
  },
  {
    document_id: 6,
    doc_type_id: 1,
    doc_code: 'LUC-SAFE-006',
    title: 'Emergency Response Procedures',
    description: 'Emergency response and incident management procedures',
    status: 'DRAFT',
    area: 'SAFETY',
    category: 'Procedure',
    confidentiality: 'INTERNAL',
    owner_role: 'Safety Manager',
    effective_date: '2024-03-15',
    keywords: 'emergency, response, incident, safety',
    tags: '["emergency", "safety", "incident"]',
    version_label: 'v1.0-draft',
    change_log: 'Initial draft for emergency procedures',
    file_path: '/uploads/docs/luc-safe-006-v1.0-draft.pdf',
    created_at: '2024-02-01T10:00:00',
    updated_at: '2024-02-03T15:30:00',
    type_name: 'Safety Manual',
  },
];

export const DUMMY_DOCUMENT_TYPES: DocumentType[] = [
  { doc_type_id: 1, type_name: 'Safety Manual', area: 'SAFETY', category: 'Manual' },
  { doc_type_id: 2, type_name: 'Training Document', area: 'TRAINING', category: 'Curriculum' },
  { doc_type_id: 3, type_name: 'SOP Document', area: 'OPERATION', category: 'Procedure' },
  { doc_type_id: 4, type_name: 'Maintenance Document', area: 'MAINTENANCE', category: 'Checklist' },
  { doc_type_id: 5, type_name: 'Security Policy', area: 'SECURITY', category: 'Policy' },
  { doc_type_id: 6, type_name: 'Compliance Document', area: 'COMPLIANCE', category: 'Manual' },
];

export const DUMMY_NOTIFICATIONS: Notifications[] = [
  {
    notification_id: 1,
    message: 'New document requires your review: Safety Management System Manual v2.1',
    procedure_name: 'document_review',
    is_read: 'N',
    created_at: '2024-02-03T10:30:00',
    sender_fullname: 'John Smith',
    sender_profile: 'Compliance Manager',
    sender_profile_code: 'COMP_MGR',
    communication_general_id: 101,
  },
  {
    notification_id: 2,
    message: 'Training curriculum has been updated and approved',
    procedure_name: 'training_update',
    is_read: 'Y',
    created_at: '2024-02-02T14:15:00',
    read_at: '2024-02-02T16:20:00',
    sender_fullname: 'Sarah Johnson',
    sender_profile: 'Training Manager',
    sender_profile_code: 'TRAIN_MGR',
    communication_general_id: 102,
  },
  {
    notification_id: 3,
    message: 'Maintenance checklist requires immediate attention',
    procedure_name: 'maintenance_alert',
    is_read: 'N',
    created_at: '2024-02-03T09:00:00',
    sender_fullname: 'Mike Davis',
    sender_profile: 'Maintenance Chief',
    sender_profile_code: 'MAINT_CHIEF',
    communication_general_id: 103,
  },
  {
    notification_id: 4,
    message: 'Your document submission has been approved',
    procedure_name: 'document_approval',
    is_read: 'Y',
    created_at: '2024-02-01T11:45:00',
    read_at: '2024-02-01T12:00:00',
    sender_fullname: 'Lisa Brown',
    sender_profile: 'Quality Assurance',
    sender_profile_code: 'QA_LEAD',
    communication_general_id: 104,
  },
];

export const DUMMY_SAFETY_INDICATORS: SafetyIndicator[] = [
  {
    id: 1,
    indicator_code: 'TRAIN_COMPLIANCE_RATE',
    indicator_type: 'KPI',
    indicator_area: 'TRAINING',
    indicator_name: 'Training Compliance Rate',
    indicator_desc: 'Percentage of required training completed on time',
    target_value: 95.00,
    unit: '%',
    frequency: 'MONTHLY',
    is_active: 1,
  },
  {
    id: 2,
    indicator_code: 'INCIDENT_RATE',
    indicator_type: 'SPI',
    indicator_area: 'OPERATIONS',
    indicator_name: 'Incident Rate',
    indicator_desc: 'Number of incidents per 1000 flight hours',
    target_value: 0.50,
    unit: 'n/1000h',
    frequency: 'MONTHLY',
    is_active: 1,
  },
  {
    id: 3,
    indicator_code: 'MAINT_ON_TIME',
    indicator_type: 'KPI',
    indicator_area: 'MAINTENANCE',
    indicator_name: 'On-Time Maintenance Completion',
    indicator_desc: 'Percentage of maintenance tasks completed within scheduled time',
    target_value: 98.00,
    unit: '%',
    frequency: 'MONTHLY',
    is_active: 1,
  },
  {
    id: 4,
    indicator_code: 'COMPLIANCE_AUDIT_SCORE',
    indicator_type: 'KPI',
    indicator_area: 'COMPLIANCE',
    indicator_name: 'Compliance Audit Score',
    indicator_desc: 'Average score from compliance audits',
    target_value: 90.00,
    unit: '%',
    frequency: 'QUARTERLY',
    is_active: 1,
  },
  {
    id: 5,
    indicator_code: 'SAFETY_REPORT_TIME',
    indicator_type: 'SPI',
    indicator_area: 'OPERATIONS',
    indicator_name: 'Safety Report Submission Time',
    indicator_desc: 'Average time to submit safety reports after incidents',
    target_value: 24.00,
    unit: 'h',
    frequency: 'MONTHLY',
    is_active: 1,
  },
  {
    id: 6,
    indicator_code: 'TRAINING_HOURS',
    indicator_type: 'KPI',
    indicator_area: 'TRAINING',
    indicator_name: 'Average Training Hours',
    indicator_desc: 'Average training hours per pilot per month',
    target_value: 8.00,
    unit: 'h',
    frequency: 'MONTHLY',
    is_active: 0,
  },
];